# Generated by Django 3.2.8 on 2021-11-08 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('author_surname', models.CharField(blank=True, max_length=254, null=True)),
                ('author_firstname', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publisher', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('isbn', models.IntegerField()),
                ('book_format', models.CharField(blank=True, max_length=254, null=True)),
                ('pages', models.CharField(blank=True, max_length=254, null=True)),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category')),
            ],
        ),
    ]
