# Generated by Django 3.2.8 on 2021-11-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211109_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_firstname',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default=(), max_length=254, null=True),
        ),
    ]
